pool:
  vmImage: 'Ubuntu 16.04'

variables:
  APP_NAME: "carts"
  ARTEFACT_ID: "sockshop/$(APP_NAME)"
  DOCKER_REGISTRY: "$(dockerRegistryEndpoint)"
  SUBSCRIPTION_ENDPOINT: "InnovationLab-Dev"

steps:
- script: |
    versionFromFile=$(cat ./version)
    theTag=$(DOCKER_REGISTRY)/$(ARTEFACT_ID)
    theDevTag=$(TAG)-$(VERSION)-$(build.buildId)
    TheStageTag=$(TAG)-$(VERSION)
    echo versionFromFile = $versionFromFile
    echo theTag = $theTag
    echo theDevTag = $theDevTag
    echo TheStageTag = $TheStageTag
    echo "##vso[task.setvariable variable=VERSION]$versionFromFile"
    echo "##vso[task.setvariable variable=TAG]$theTag"
    echo "##vso[task.setvariable variable=DEV_TAG]$theDevTag"
    echo "##vso[task.setvariable variable=TAG_STAGING]$TheStageTag"
    echo VERSION = $VERSION
    echo TAG = $TAG
    echo DEV_TAG = $DEV_TAG
    echo TAG_STAGING = $TAG_STAGING

- script: |
    echo versionFromFile = $versionFromFile
    echo theTag = $theTag
    echo theDevTag = $theDevTag
    echo TheStageTag = $TheStageTag
    echo VERSION = $VERSION
    echo TAG = $TAG
    echo DEV_TAG = $DEV_TAG
    echo TAG_STAGING = $TAG_STAGING

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: $(TAG_DEV)

- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: $(SUBSCRIPTION_ENDPOINT)
    azureContainerRegistry: $(DOCKER_REGISTRY)
    command: login

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: $(SUBSCRIPTION_ENDPOINT)
    azureContainerRegistry: $(DOCKER_REGISTRY)
    command: 'push'
    imageName: $(TAG_DEV)

- script: |
    sed -i 's#image: .*#image: $(TAG_DEV)#' manifest/$(APP_NAME).yml

- task: CopyFiles@2
  inputs:
    contents: manifest/*
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Yaml