# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=vsts
# https://github.com/acm-jjahn/carts/blob/master/Jenkinsfile
#TAG = "$(DOCKER_REGISTRY_URL):5000/library/$(ARTEFACT_ID)"
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  APP_NAME: "carts"
  VERSION: "1"
  ARTEFACT_ID: "sockshop/$(APP_NAME)"
  DOCKER_REGISTRY_URL: "rjahndemoregistry.azurecr.io"
  DOCKER_REGISTRY: "rjahndemoregistry.azurecr.io"
  SUBSCRIPTION_ENDPOINT: "rjahn-demo-acm"
  TAG: "$(DOCKER_REGISTRY_URL):5000/library/$(ARTEFACT_ID)"
  TAG_DEV: "$(TAG)-$(VERSION)-$(build.buildId)"
  TAG_STAGING: "$(TAG)-$(VERSION)"

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: $(TAG_DEV)

- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: $(SUBSCRIPTION_ENDPOINT)
    azureContainerRegistry: $(DOCKER_REGISTRY)
    command: login

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: $(SUBSCRIPTION_ENDPOINT)
    azureContainerRegistry: $(DOCKER_REGISTRY)
    command: 'push'
